# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://www.xiadongblog.com
date_format: "ordinal"
title: 夏冬博客
subtitle: "分享技术，体会生活"
description: "夏冬的个人博客"
keywords: 夏冬, Xia Dong, xiadongShadow, xiadong
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Xia Dong
organization: 
organization_url: 
github_username: xiadongShadow
location: Xi'an, China
email: xiadong332@icloud.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: xiadongShadow/xiadongblog.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: xiadongShadow
    repo: blog-comments
    oauth:
        client_id: f39859e7e0ecf5c5d0ca
        client_secret: b192048cf9c38302e5b268952ad2ee7699967cff
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: xiadongShadow
    repo: blog-comments
    clientID: f39859e7e0ecf5c5d0ca
    clientSecret: b192048cf9c38302e5b268952ad2ee7699967cff
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
